# Site settings
title: The Freshman's Guide - Index
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
highlighter: pygments
baseurl: "guide.wona.co.in" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  ankg

# Build settings
markdown: rdiscount
permalink: /:categories/:title
rdiscount:
  extensions: [smart]

